config/routes.rb
Rails.application.routes.draw do

  resources :transactions, only: [:new, :create]
  resources :subscriptions, only: [:index, :new, :create]

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :contacts do
    resources :properties
    resources :calls
    
    collection do
      post :import
      get :database
    end
  end

  resources :charges, only: [:new, :create]

  get 'static/home'
  get 'about', to: 'static#about', as: :static_about

  root to: 'static#home'
end

app/models/call.rb
class Call < ActiveRecord::Base
  belongs_to :contact
  belongs_to :dial
  belongs_to :conversation
  belongs_to :investing
  belongs_to :timing
  belongs_to :motivator
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  belongs_to :dial
  belongs_to :conversation
  belongs_to :investing
  belongs_to :timing
  belongs_to :motivator
  has_many :properties, dependent: :destroy
  has_many :calls, dependent: :destroy

  accepts_nested_attributes_for :calls

  validates :name, presence: true

  # default_scope { order('updated_at ASC') }

  # scope :next, lambda { |id| where("id > ?", id).order("id ASC") }
  # scope :previous, lambda { |id| where("id < ?", id).order("id DESC") }

  searchkick

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Contact.create! row.to_hash
    end
  end

  def previous
    if self.id == 1
      User.current.contacts.last
    else
      User.current.contacts.where("id < ?", self.id).last
    end
  end

  def next
    if self == User.current.contacts.last
      User.current.contacts.first
    else
      User.current.contacts.where("id > ?", self.id).first
    end
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/dial.rb
class Dial < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/investing.rb
class Investing < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/motivator.rb
class Motivator < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  validates :stripe_id, uniqueness: true
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :contact
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan
end

app/models/timing.rb
class Timing < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :contacts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  def premium?
    role == 'premium'
  end

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController

  def index
    @contact = Contact.find(params[:contact_id])
    @calls = @contact.calls
  end

  def show
    @contact = Contact.find(params[:contact_id])
    @call = Call.new
  end

  def new
    @contact = Contact.find(params[:contact_id])
    @call = Call.new
  end

  def edit
    @contact = Contact.find(params[:contact_id])
    @call = Call.find(params[:id])
    redirect_to edit_contact_path(@contact)
  end

  def create
    @contact = Contact.find(params[:contact_id])
    @call = Call.new(call_params)
    @call.contact_id = @contact.id
    @call.user_id = current_user.id

    if @call.save
      flash[:notice] = "Your Call was successfully posted."
      redirect_to edit_contact_path(@contact)
    else
      flash[:error] = "Your Call was not posted. Please try again."
      redirect_to edit_contact_path(@contact)
    end
  end

  def update
    @contact = Contact.find(params[:contact_id])
    @call = Call.find(params[:id])
    redirect_to edit_contact_path(@contact)
  end

  def destroy
    @contact = Contact.find(params[:contact_id])
    @call = Call.find(params[:id])
    @call.destroy
    redirect_to edit_contact_path(@contact)
  end

  private
    def call_params
      params.require(:call).permit(:contact_id, :user_id, :dial_id, :conversation_id, :investing_id, :timing_id, :motivator_id)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_filter :authenticate_user!

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
    authorize @properties
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @contact = Contact.find(params[:contact_id])
    @property = Property.find(params[:id])
    authorize @property
  end

  # GET /properties/new
  def new
    @contact = Contact.find(params[:contact_id])
    @property = Property.new
    authorize @property
  end

  # GET /properties/1/edit
  def edit
    @contact = Contact.find(params[:contact_id])
    @property = Property.find(params[:id])
    authorize @property
  end

  # POST /properties
  # POST /properties.json
  def create
    @contact = Contact.find(params[:contact_id])
    @property = Property.new(property_params)
    @property.contact = @contact
    authorize @property

    respond_to do |format|
      if @property.save
        format.html { redirect_to edit_contact_path(@contact), notice: 'Property was successfully created.' }
        format.json { redirect_to edit_contact_path(@contact), status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    @contact = Contact.find(params[:contact_id])
    @property = Property.find(params[:id])
    authorize @property

    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to edit_contact_path(@contact), notice: 'Property was successfully updated.' }
        format.json { redirect_to edit_contact_path(@contact), status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @contact = Contact.find(params[:contact_id])
    @property = Property.find(params[:id])
    authorize @property
    @property.destroy
    respond_to do |format|
      format.html { redirect_to edit_contact_path(@contact), notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def property_params
      params.require(:property).permit(:street_no, :street, :city, :state, :zip, :year_built, :units, :purchase_year, :contact_id)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/properties/_form.html.haml
= form_for [@contact, @property] do |f|
  .row
    .col-md-6.col-md-offset-3
      - if @property.errors.any?
        #error_explanation
          %h2= "#{pluralize(@property.errors.count, "error")} prohibited this property from being saved:"
          %ul
            - @property.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        = f.label :street_no
        = f.number_field :street_no, class: 'form-control'
      .form-group
        = f.label :street
        = f.text_field :street, class: 'form-control'
      .form-group
        = f.label :city
        = f.text_field :city, class: 'form-control'
      .form-group
        = f.label :state
        = f.text_field :state, class: 'form-control'
      .form-group
        = f.label :zip
        = f.number_field :zip, class: 'form-control'
      .form-group
        = f.label :year_built
        = f.number_field :year_built, class: 'form-control'
      .form-group
        = f.label :units
        = f.number_field :units, class: 'form-control'
      .form-group
        = f.label :purchase_year
        = f.number_field :purchase_year, class: 'form-control'
      .actions
        = f.submit 'Save', class: 'btn btn-success'

app/views/properties/edit.html.haml
%h1 Edit Property
  
= render 'form'

app/views/properties/index.html.haml
%h1 Listing properties

%table
  %tr
    %th Street no
    %th Street
    %th City
    %th State
    %th Zip
    %th Year built
    %th Units
    %th Purchase year
    %th Contact
    %th
    %th
    %th

  - @properties.each do |property|
    %tr
      %td= property.street_no
      %td= property.street
      %td= property.city
      %td= property.state
      %td= property.zip
      %td= property.year_built
      %td= property.units
      %td= property.purchase_year
      %td= property.contact
      %td= link_to 'Show', property
      %td= link_to 'Edit', edit_property_path(property)
      %td= link_to 'Destroy', property, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Property', new_property_path

app/views/properties/new.html.haml
%h3.text-center= "Add a property to #{@contact.name}" 
= render 'form'

app/views/properties/show.html.haml
%p#notice= notice

%p
  %b Street no:
  = @property.street_no
%p
  %b Street:
  = @property.street
%p
  %b City:
  = @property.city
%p
  %b State:
  = @property.state
%p
  %b Zip:
  = @property.zip
%p
  %b Year built:
  = @property.year_built
%p
  %b Units:
  = @property.units
%p
  %b Purchase year:
  = @property.purchase_year
%p
  %b Contact:
  = @property.contact