config/routes.rb
Rails.application.routes.draw do

  resources :transactions, only: [:new, :create]
  resources :subscriptions, only: [:index, :new, :create]

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :contacts do
    resources :properties
    resources :calls
    
    collection do
      post :import
      get :database
    end
  end

  resources :charges, only: [:new, :create]

  get 'static/home'
  get 'about', to: 'static#about', as: :static_about

  root to: 'static#home'
end

app/models/call.rb
class Call < ActiveRecord::Base
  belongs_to :contact
  belongs_to :dial
  belongs_to :conversation
  belongs_to :investing
  belongs_to :timing
  belongs_to :motivator
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  belongs_to :dial
  belongs_to :conversation
  belongs_to :investing
  belongs_to :timing
  belongs_to :motivator
  has_many :properties, dependent: :destroy
  has_many :calls, dependent: :destroy

  accepts_nested_attributes_for :calls

  validates :name, presence: true

  # default_scope { order('updated_at ASC') }

  # scope :next, lambda { |id| where("id > ?", id).order("id ASC") }
  # scope :previous, lambda { |id| where("id < ?", id).order("id DESC") }

  searchkick

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Contact.create! row.to_hash
    end
  end

  def previous
    if self.id == 1
      User.current.contacts.last
    else
      User.current.contacts.where("id < ?", self.id).last
    end
  end

  def next
    if self == User.current.contacts.last
      User.current.contacts.first
    else
      User.current.contacts.where("id > ?", self.id).first
    end
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/dial.rb
class Dial < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/investing.rb
class Investing < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/motivator.rb
class Motivator < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  validates :stripe_id, uniqueness: true
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :contact
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan
end

app/models/timing.rb
class Timing < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :contacts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  def premium?
    role == 'premium'
  end

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController

  def index
    @contact = Contact.find(params[:contact_id])
    @calls = @contact.calls
  end

  def show
    @contact = Contact.find(params[:contact_id])
    @call = Call.new
  end

  def new
    @contact = Contact.find(params[:contact_id])
    @call = Call.new
  end

  def edit
    @contact = Contact.find(params[:contact_id])
    @call = Call.find(params[:id])
    redirect_to edit_contact_path(@contact)
  end

  def create
    @contact = Contact.find(params[:contact_id])
    @call = Call.new(call_params)
    @call.contact_id = @contact.id
    @call.user_id = current_user.id

    if @call.save
      flash[:notice] = "Your Call was successfully posted."
      redirect_to edit_contact_path(@contact)
    else
      flash[:error] = "Your Call was not posted. Please try again."
      redirect_to edit_contact_path(@contact)
    end
  end

  def update
    @contact = Contact.find(params[:contact_id])
    @call = Call.find(params[:id])
    redirect_to edit_contact_path(@contact)
  end

  def destroy
    @contact = Contact.find(params[:contact_id])
    @call = Call.find(params[:id])
    @call.destroy
    redirect_to edit_contact_path(@contact)
  end

  private
    def call_params
      params.require(:call).permit(:contact_id, :user_id, :dial_id, :conversation_id, :investing_id, :timing_id, :motivator_id)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_current_user

  def database
  end

  def import
    Contact.import(params[:file])
    redirect_to contacts_path, notice: "Contacts imported."
  end

  def index
    if params[:query].present?
      @contacts = current_user.contacts.paginate(page: params[:page], per_page: 50).search(params[:query])
    else
      @contacts = current_user.contacts.all.paginate(page: params[:page], per_page: 50)
    end
    authorize @contacts
  end

  def show
    @contact = Contact.find(params[:id])
    @new_call = @contact.calls.build
    redirect_to edit_contact_path(@contact)
  end

  def new
    @contact = Contact.new
    authorize @contact
  end

  def edit
    @contact = Contact.find(params[:id])
    @user = @contact.user
    authorize @contact
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id

    authorize @contact
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :edit, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @contact = Contact.find(params[:id])
    authorize @contact
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { render :edit, notice: 'Contact was successfully updated.' }
        format.json { render :edit }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    authorize @contact
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :entity, :phone, :alt_phone, :dead_phone, :email, :alt_email, :dead_email, :dial_id, :conversation_id, :investing_id, :timing_id, :motivator_id, :body, :user_id)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/contacts/_form.html.haml
= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-4
      %h3 Contact details
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :entity
        = f.text_field :entity, class: 'form-control'
      .form-group
        = f.label :phone
        = f.text_field :phone, class: 'form-control'
      .form-group
        = f.label :alt_phone
        = f.text_field :alt_phone, class: 'form-control'
      .form-group
        = f.label :dead_phone
        = f.text_field :dead_phone, class: 'form-control'
      .form-group
        = f.label :email
        = f.text_field :email, class: 'form-control'
      .form-group
        = f.label :alt_email
        = f.text_field :alt_email, class: 'form-control'
      .form-group
        = f.label :dead_email
        = f.text_field :dead_email, class: 'form-control'
    .col-md-4
      - if @contact.id?
        %h3 Property details
        = link_to "Add property", new_contact_property_path(@contact)
        - @contact.properties.each do |property|
          %p.lead= "#{property.street_no} #{property.street}"
          %p.lead= "#{property.city}, #{property.state} #{property.zip}"
          %p
            %b Units:
            = property.units
          %p
            %b Year built:
            = property.year_built
          %p
            %b Purchase year:
            = property.purchase_year
          = link_to "Edit", edit_contact_property_path(@contact, property), class: 'btn btn-primary btn-sm'
          = link_to "Delete", [@contact, property], method: :delete, data: { confirm: 'Are you sure you want to delete this property?' }, class: 'btn btn-danger btn-sm'


    .col-md-4
      - if @contact.id?
        %h3 Call result
        .form-group
          = f.label :dial
          = f.select :dial_id, options_from_collection_for_select(Dial.all, "id", "result"), class: 'form-control'
        .form-group
          = f.label :conversation
          = f.select :conversation_id, options_from_collection_for_select(Conversation.all, "id", "result")
        .form-group
          = f.label :investing
          = f.select :investing_id, options_from_collection_for_select(Investing.all, "id", "result")
        .form-group
          = f.label :timing
          = f.select :timing_id, options_from_collection_for_select(Timing.all, "id", "result")
        .form-group
          = f.label :motivator
          = f.select :motivator_id, options_from_collection_for_select(Motivator.all, "id", "result")
        .form-group
          = f.label :notes
          = f.text_area :body, class: 'form-control', rows: 6
        .actions
          = f.submit 'Save', class: 'btn btn-success'

app/views/contacts/database.html.haml
.row
  .col-md-6.col-md-offset-3
    %p Import your contact database via CSV file
    %p The top row sets Contact attributes (user_id, name, entity, phone, email)
    %p= "The first column must be populated with your unique user id. #{current_user.name} id: #{current_user.id}"
    %br
    %h5 Sample CSV file
    = image_tag "http://i1381.photobucket.com/albums/ah208/Ching_Casanova_Tapia/ScreenShot2014-12-25at42457PM_zps6829df73.png"
    %br
    %br
    %br
    %p Or save an Excel spreadsheet as a CSV file
    %h5 Sample spreadsheet, saved as .csv
    = image_tag "http://i1381.photobucket.com/albums/ah208/Ching_Casanova_Tapia/ScreenShot2014-12-25at42546PM_zps89e16097.png"
    %br
    %br
    %br
    = form_tag import_contacts_path, multipart: true do
      = file_field_tag :file
      %br
      = submit_tag "Import", class: 'btn btn-success btn-sm'

app/views/contacts/edit.html.haml
- if @contact.calls.last
  .text-right
    %h3.status= "status: #{@contact.calls.last.investing.result}, #{@contact.calls.last.timing.result}"
.row
  .col-md-1
    = link_to edit_contact_path(@contact.previous), class: 'btn' do
      %i.glyphicon.glyphicon-chevron-left
  .col-md-10
    = form_for @contact do |f|
      - if @contact.errors.any?
        #error_explanation
          %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
          %ul
            - @contact.errors.full_messages.each do |msg|
              %li= msg
      .row
        .col-md-4
          %h4 Contact details
          .form-group
            = f.label :name
            = f.text_field :name, class: 'form-control'
          .form-group
            = f.label :entity
            = f.text_field :entity, class: 'form-control'
          .form-group
            = f.label :phone
            = f.text_field :phone, class: 'form-control'
          .form-group
            = f.label :alt_phone
            = f.text_field :alt_phone, class: 'form-control'
          .form-group
            = f.label :dead_phone
            = f.text_field :dead_phone, class: 'form-control'
          .form-group
            = f.label :email
            = f.text_field :email, class: 'form-control'
          .form-group
            = f.label :alt_email
            = f.text_field :alt_email, class: 'form-control'
          .form-group
            = f.label :dead_email
            = f.text_field :dead_email, class: 'form-control'
          .form-group
            = f.label :notes
            = f.text_area :body, class: 'form-control', rows: 6
          .form-group
            = f.submit 'Save', class: 'btn btn-success'
        .col-md-4
          %h4 Property details
          = link_to "Add property", new_contact_property_path(@contact)
          %br
          %br
          - @contact.properties.each do |property|
            %p= "#{property.street_no} #{property.street}"
            %p= "#{property.city}, #{property.state} #{property.zip}"
            %p
              %b Units:
              = property.units
            %p
              %b Year built:
              = property.year_built
            %p
              %b Purchase year:
              = property.purchase_year
            = link_to "Edit", edit_contact_property_path(@contact, property), class: 'btn btn-primary btn-sm'
            = link_to "Delete", [@contact, property], method: :delete, data: { confirm: 'Are you sure you want to delete this property?' }, class: 'btn btn-danger btn-sm'

        .col-md-4
          %h4 Call
          = link_to "Call History", contact_calls_path(@contact)
          %br
          = link_to "New Call", new_contact_call_path(@contact)
          %br
          %br
          - if @contact.calls.last
            %h4= "Last call on #{@contact.calls.last.created_at.strftime("%m/%d/%Y")}"
            %p
              %b Dial:
              = @contact.calls.last.dial.result
            %p
              %b Conversation:
              = @contact.calls.last.conversation.result
            %p
              %b Investing?
              = @contact.calls.last.investing.result
            %p
              %b Timing:
              = @contact.calls.last.timing.result
            %p
              %b Motivator:
              = @contact.calls.last.motivator.result

  .col-md-1
    = link_to edit_contact_path(@contact.next), class: 'btn' do
      %i.glyphicon.glyphicon-chevron-right

app/views/contacts/index.html.haml
- if current_user.contacts.first
  .row
    .col-md-4
      = link_to "Import Contacts", database_contacts_path, class: 'btn btn-primary btn-sm'
      = link_to "Add Contact", new_contact_path, class: 'btn btn-success btn-sm'
    .col-md-3
      = form_tag contacts_path, class: "form-inline", method: :get do
        .form-group
          = text_field_tag :query, params[:query], class: "form-control"
        = submit_tag "Search", class: "btn btn-primary"
        - if params[:query].present?
          = link_to "clear", contacts_path
  %br
  %br
  %br

  .row
    .col-md-2
      %b Contact Name
    .col-md-2
      %b Company
    .col-md-2
      %b Phone
    .col-md-3
      %b Email
    .col-md-1
      %b Status
    .col-md-1
      %b Timing
    .col-md-1
      %b Motivator
  - @contacts.each do |contact|
    .row
      .col-md-2
        %p= link_to contact.name, edit_contact_path(contact)
      .col-md-2
        %small= contact.entity
      .col-md-2
        = contact.phone
      .col-md-3
        = mail_to contact.email
      .col-md-1
        = contact.calls.last.investing.result if contact.calls.last && contact.calls.last.investing
      .col-md-1
        = contact.calls.last.timing.result if contact.calls.last && contact.calls.last.timing
      .col-md-1
        = contact.calls.last.motivator.result if contact.calls.last && contact.calls.last.motivator

  = will_paginate @contacts
- else
  .text-center
    %p Upload your first contact, or import your database
    = link_to "Import Contacts", database_contacts_path, class: 'btn btn-primary btn-sm'
    = link_to "Add Contact", new_contact_path, class: 'btn btn-success btn-sm'

app/views/contacts/new.html.haml
%h1.text-center New contact

= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-4.col-md-offset-4
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :entity
        = f.text_field :entity, class: 'form-control'
      .form-group
        = f.label :phone
        = f.text_field :phone, class: 'form-control'
      .form-group
        = f.label :alt_phone
        = f.text_field :alt_phone, class: 'form-control'
      .form-group
        = f.label :dead_phone
        = f.text_field :dead_phone, class: 'form-control'
      .form-group
        = f.label :email
        = f.text_field :email, class: 'form-control'
      .form-group
        = f.label :alt_email
        = f.text_field :alt_email, class: 'form-control'
      .form-group
        = f.label :dead_email
        = f.text_field :dead_email, class: 'form-control'
      .actions
        = f.submit 'Save', class: 'btn btn-success'

app/views/contacts/show.html.haml
%p#notice= notice

.row
  .col-md-4
    %p
      %b Name:
      = @contact.name
    %p
      %b Entity:
      = @contact.entity
    %p
      %b Phone:
      = @contact.phone
    %p
      %b Alt phone:
      = @contact.alt_phone
    %p
      %b Dead phone:
      = @contact.dead_phone
    %p
      %b Email:
      = @contact.email
    %p
      %b Alt email:
      = @contact.alt_email
    %p
      %b Dead email:
      = @contact.dead_email
    %p  
      %b Notes:
      = @contact.body