config/routes.rb
Rails.application.routes.draw do

  resources :transactions, only: [:new, :create]
  resources :subscriptions, only: [:index, :new, :create]

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :contacts do
    resources :properties
    resources :calls
    
    collection do
      post :import
      get :database
    end
  end

  resources :charges, only: [:new, :create]

  get 'static/home'
  get 'about', to: 'static#about', as: :static_about

  root to: 'static#home'
end

app/models/call.rb
class Call < ActiveRecord::Base
  belongs_to :contact
  belongs_to :dial
  belongs_to :conversation
  belongs_to :investing
  belongs_to :timing
  belongs_to :motivator
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  belongs_to :dial
  belongs_to :conversation
  belongs_to :investing
  belongs_to :timing
  belongs_to :motivator
  has_many :properties, dependent: :destroy
  has_many :calls, dependent: :destroy

  accepts_nested_attributes_for :calls

  validates :name, presence: true

  # default_scope { order('updated_at ASC') }

  # scope :next, lambda { |id| where("id > ?", id).order("id ASC") }
  # scope :previous, lambda { |id| where("id < ?", id).order("id DESC") }

  searchkick

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Contact.create! row.to_hash
    end
  end

  def previous
    if self.id == 1
      User.current.contacts.last
    else
      User.current.contacts.where("id < ?", self.id).last
    end
  end

  def next
    if self == User.current.contacts.last
      User.current.contacts.first
    else
      User.current.contacts.where("id > ?", self.id).first
    end
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/dial.rb
class Dial < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/investing.rb
class Investing < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/motivator.rb
class Motivator < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  validates :stripe_id, uniqueness: true
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :contact
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan
end

app/models/timing.rb
class Timing < ActiveRecord::Base
  has_many :contacts
  has_many :calls
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :contacts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  def premium?
    role == 'premium'
  end

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController

  def index
    @contact = Contact.find(params[:contact_id])
    @calls = @contact.calls
  end

  def show
    @contact = Contact.find(params[:contact_id])
    @call = Call.new
  end

  def new
    @contact = Contact.find(params[:contact_id])
    @call = Call.new
  end

  def edit
    @contact = Contact.find(params[:contact_id])
    @call = Call.find(params[:id])
    redirect_to edit_contact_path(@contact)
  end

  def create
    @contact = Contact.find(params[:contact_id])
    @call = Call.new(call_params)
    @call.contact_id = @contact.id
    @call.user_id = current_user.id

    if @call.save
      flash[:notice] = "Your Call was successfully posted."
      redirect_to edit_contact_path(@contact)
    else
      flash[:error] = "Your Call was not posted. Please try again."
      redirect_to edit_contact_path(@contact)
    end
  end

  def update
    @contact = Contact.find(params[:contact_id])
    @call = Call.find(params[:id])
    redirect_to edit_contact_path(@contact)
  end

  def destroy
    @contact = Contact.find(params[:contact_id])
    @call = Call.find(params[:id])
    @call.destroy
    redirect_to edit_contact_path(@contact)
  end

  private
    def call_params
      params.require(:call).permit(:contact_id, :user_id, :dial_id, :conversation_id, :investing_id, :timing_id, :motivator_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Call Carousel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
  $(function(){
    Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');
  });
  </script>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Call Carousel", root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <!-- <li><%= link_to "About", static_about_path %></li> -->
          <% if current_user && current_user.contacts.first %>
            <li><%= link_to "Carousel", edit_contact_path(current_user.contacts.first) %></li>
          <% else %>
            <li><%= link_to "Carousel", contacts_path %></li>
          <% end %>
          <li><%= link_to "Contacts", contacts_path %></li>
          <% if current_user %>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li> -->
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <!-- Flash messages  -->
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

  <!-- Main content -->
  <div id="content" class="container">
    <%= yield %>
  </div>

  <!-- Footer -->


</body>
</html>